stages:
  prepare:
    cmd: python3.12 src/prepare.py data/raw/btc_ohlcv_long_5min.csv 
      data/prepared
    deps:
    - data/raw
    - src/prepare.py
    - src/utils/seed.py
    params:
    - prepare
    outs:
    - data/prepared
  train:
    cmd: python3.12 src/train.py data/prepared model
    deps:
    - data/prepared
    - src/train.py
    - src/utils/seed.py
    params:
    - train
    outs:
    - model
  evaluate:
    cmd: python3.12 src/evaluate.py model data/prepared
    deps:
    - model
    - src/evaluate.py
    metrics:
    - evaluation/metrics.json
    plots:
    - evaluation/plots/pred_vs_true.png
    - evaluation/plots/training_history.png
