feeder:
  pairs: ["BTC/USDT"]        # Trading pairs to fetch from Binance
  interval: "1h"             # Candle interval (1m, 1h, 1d)
  months: 1                  # Number of months of historical data to retrieve
  output_path: "ohlcv-data"  # Subfolder inside the bucket (optional)

training:
  epochs: 20                 # Number of training epochs
  batch_size: 128            # Training batch size
  data_prefix: "gs://bucket-crypto-data/ohlcv-data"  # Path to input training data
